package com.wow.timewalkers.enums;

public enum WowRace {
    HUMAN, ORC, DWARF, GNOME, NIGHT_ELF, DRAENEI, WORGEN,
    VOID_ELF, LIGHTFORGED_DRAENEI, KUL_TIRAN, DARK_IRON_DWARF, MECHAGNOME,
    TROLL, TAUREN, UNDEAD, BLOOD_ELF, GOBLIN,
    NIGHTBORNE, HIGHMOUNTAIN_TAUREN, MAGHAR_ORC, VULPERA, ZANDALARI_TROLL,
    PANDAREN,
    DRACTHYR,
    EARTHEN,
    HARANIR
}
