TRUNCATE TABLE armor_pieces, weapons RESTART IDENTITY CASCADE;

-- =============================================================
-- ARMOR PIECES
-- Columns: armor_type, slot, name, expansion, primary_stat,
--          secondary_stat, cost, notes, wowhead_url
-- =============================================================

INSERT INTO armor_pieces (armor_type, slot, name, expansion, primary_stat, secondary_stat, cost, notes, wowhead_url, icon_url)
VALUES

-- Plate - Head
('Plate', 'Head', 'Mugthol''s Helm', 'Classic', 'Mastery', 'Crit', 25, NULL,
 'https://www.wowhead.com/item=224856/mugthols-helm?bonus=11072', 'https://wow.zamimg.com/images/wow/icons/large/inv_helmet_25.jpg'),
('Plate', 'Head', 'Faceguard of Determination', 'Burning Crusade', 'Haste', 'Crit', 25, NULL,
 'https://www.wowhead.com/item=129835/faceguard-of-determination?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_helmet_01.jpg'),
('Plate', 'Head', 'Mo''gruth''s Discarded Parade Helm', 'Warlords of Draenor', 'Haste', 'Mastery', 25, NULL,
 'https://www.wowhead.com/item=127320/mogruths-discarded-parade-helm?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_helm_plate_draenorhonors2_c_01_paladin.jpg'),
('Plate', 'Head', 'Animaforged Sentinel''s Helm', 'Shadowlands', 'Crit', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=256355/animaforged-sentinels-helm?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_plate_oribosdungeon_c_01_helm.jpg'),
-- Plate - Shoulders
('Plate', 'Shoulders', 'Stonetoe Spaulders', 'Mists of Pandaria', 'Crit', 'Haste', 35, NULL,
 'https://www.wowhead.com/item=144063/stonetoe-spaulders?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_shoulder_plate_reputation_c_01.jpg'),
('Plate', 'Shoulders', 'Black Rook Elite Shoulderplates', 'Legion', 'Crit', 'Mastery', 35, NULL,
 'https://www.wowhead.com/item=187590/black-rook-elite-shoulderplates?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_shoulder_plate_lordravencrest_b_01.jpg'),
('Plate', 'Shoulders', 'Boralus Cityguard Spaulders', 'Battle for Azeroth', 'Mastery', 'Crit', 35, NULL,
 'https://www.wowhead.com/item=243564/boralus-cityguard-spaulders?bonus=12264', 'https://wow.zamimg.com/images/wow/icons/large/inv_shoulder_plate_kultirasdungeon_c_01.jpg'),
-- Plate - Chest
('Plate', 'Chest', 'Ogre Captain''s Armor', 'Classic', 'Haste', 'Vers', 25, NULL,
 'https://www.wowhead.com/item=234862/ogre-captains-armor?bonus=11072', 'https://wow.zamimg.com/images/wow/icons/large/inv_chest_chain_14.jpg'),
('Plate', 'Chest', 'Castle Breaker''s Battleplate', 'Wrath of the Lich King', 'Haste', 'Crit', 25, NULL,
 'https://www.wowhead.com/item=129889/castle-breakers-battleplate?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_chest_plate_25.jpg'),
('Plate', 'Chest', 'Bones of the Damned', 'Cataclysm', 'Crit', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=133525/bones-of-the-damned?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_chest_plate_raiddeathknight_k_01.jpg'),
('Plate', 'Chest', 'Black Rook Elite Chestguard', 'Legion', 'Haste', 'Mastery', 25, NULL,
 'https://www.wowhead.com/item=187588/black-rook-elite-chestguard?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_chest_plate_lordravencrest_b_01.jpg'),
('Plate', 'Chest', 'Animaforged Sentinel''s Plate', 'Shadowlands', 'Vers', 'Crit', 25, NULL,
 'https://www.wowhead.com/item=256350/animaforged-sentinels-plate?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_plate_oribosdungeon_c_01_chest.jpg'),
-- Plate - Wrist
('Plate', 'Wrist', 'Runed Golem Shackles', 'Classic', 'Crit', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=225184/runed-golem-shackles?bonus=11072', 'https://wow.zamimg.com/images/wow/icons/large/inv_bracer_17.jpg'),
('Plate', 'Wrist', 'Flashing Cracers of Warmth', 'Cataclysm', 'Mastery', 'Crit', 25, NULL,
 'https://www.wowhead.com/item=133533/flashing-bracers-of-warmth?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_bracer_plate_raidpaladin_k_01.jpg'),
('Plate', 'Wrist', 'Pilfered Wristguards of Aka''ali', 'Battle for Azeroth', 'Haste', 'Mastery', 25, NULL,
 'https://www.wowhead.com/item=243559/pilfered-wristguards-of-akaali?bonus=12264', 'https://wow.zamimg.com/images/wow/icons/large/inv_bracer_plate_zandalarquest_b_01.jpg'),
-- Plate - Hands
('Plate', 'Hands', 'Gauntlets of the Kraken', 'Wrath of the Lich King', 'Crit', 'Vers', 25, NULL,
 'https://www.wowhead.com/item=129880/gauntlets-of-the-kraken?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_gauntlets_86.jpg'),
('Plate', 'Hands', 'Gauntlets of Jade Sutras', 'Mists of Pandaria', 'Crit', 'Mastery', 25, NULL,
 'https://www.wowhead.com/item=144047/gauntlets-of-jade-sutras?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_glove_plate_reputation_c_01.jpg'),
('Plate', 'Hands', 'Krag''goth''s Iron Gauntlets', 'Warlords of Draenor', 'Haste', 'Mastery', 25, NULL,
 'https://www.wowhead.com/item=127319/kraggoths-iron-gauntlets?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_plate_blackrockclan_b_01glove.jpg'),
-- Plate - Waist
('Plate', 'Waist', 'Girdle of Seething Rage', 'Burning Crusade', 'Haste', 'Crit', 25, NULL,
 'https://www.wowhead.com/item=129854/girdle-of-seething-rage?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_belt_13.jpg'),
('Plate', 'Waist', 'Blinding Girdle of Truth', 'Cataclysm', 'Mastery', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=133531/blinding-girdle-of-truth?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_belt_plate_raidpaladin_k_01.jpg'),
('Plate', 'Waist', 'Krud''s Girthy Girdle', 'Warlords of Draenor', 'Crit', 'Vers', 25, NULL,
 'https://www.wowhead.com/item=119384/kruds-girthy-girdle?bonus=4811:10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_belt_plate_draenordungeon_c_01.jpg'),
-- Plate - Legs
('Plate', 'Legs', 'Legplates of Unending Fury', 'Burning Crusade', 'Haste', 'Crit', 25, NULL,
 'https://www.wowhead.com/item=129842/legplates-of-unending-fury?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_pants_plate_21.jpg'),
('Plate', 'Legs', 'Ambersmith Legplates', 'Mists of Pandaria', 'Crit', 'Mastery', 25, NULL,
 'https://www.wowhead.com/item=144059/ambersmith-legplates?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_pants_plate_reputation_c_01.jpg'),
('Plate', 'Legs', 'Hershak''s Heavy Legguards', 'Warlords of Draenor', 'Vers', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=119382/hershaks-heavy-legguards?bonus=4811:10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_pant_plate_draenorquest95_b_01.jpg'),
('Plate', 'Legs', 'Black Rook Elite Legguards', 'Legion', 'Vers', 'Crit', 25, NULL,
 'https://www.wowhead.com/item=187589/black-rook-elite-legguards?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_pant_plate_lordravencrest_b_01.jpg'),
-- Plate - Feet
('Plate', 'Feet', 'Boots of Avoidance', 'Classic', 'Haste', 'Vers', 25, 'Have a small amount of Avoidance',
 'https://www.wowhead.com/item=224860/boots-of-avoidance?bonus=11072', 'https://wow.zamimg.com/images/wow/icons/large/inv_boots_plate_05.jpg'),
('Plate', 'Feet', 'Kyzoc''s Ground Stompers', 'Wrath of the Lich King', 'Crit', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=129868/kyzocs-ground-stompers?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_boots_plate_08.jpg'),
('Plate', 'Feet', 'Yu''lon Guardian Boots', 'Mists of Pandaria', 'Crit', 'Mastery', 25, NULL,
 'https://www.wowhead.com/item=144048/yulon-guardian-boots?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_boot_plate_reputation_c_01.jpg'),

-- Mail - Head
('Mail', 'Head', 'Helm of Narv', 'Classic', 'Crit', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=224855/helm-of-narv?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_helmet_05.jpg'),
('Mail', 'Head', 'Storm Master''s Helmet', 'Burning Crusade', 'Crit', NULL, 25, NULL,
 'https://www.wowhead.com/item=129838/storm-masters-helmet?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_helmet_69.jpg'),
('Mail', 'Head', 'Dented Ogre Skullcap', 'Warlords of Draenor', 'Crit', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=112096/dented-ogre-skullcap?bonus=4811:12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_mail_draenorquest90_b_01helm.jpg'),
('Mail', 'Head', 'Elysian Pathfinder''s Visor', 'Shadowlands', 'Haste', 'Mastery', 25, NULL,
 'https://www.wowhead.com/item=256358/elysian-pathfinders-visor?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_helm_mail_oribosdungeon_c_01.jpg'),
-- Mail - Shoulders
('Mail', 'Shoulders', 'Windwalker Spaulders', 'Mists of Pandaria', 'Haste', 'Crit', 35, NULL,
 'https://www.wowhead.com/item=144062/windwalker-spaulders?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_shoulder_mail_reputation_c_01.jpg'),
('Mail', 'Shoulders', 'Leyguard Mantle', 'Legion', 'Mastery', 'Haste', 35, NULL,
 'https://www.wowhead.com/item=187587/leyguard-mantle?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_shoulder_mail_legionendgame_c_01.jpg'),
('Mail', 'Shoulders', 'Navigator''s Flagship Mantle', 'Battle for Azeroth', 'Crit', 'Mastery', 35, NULL,
 'https://www.wowhead.com/item=243565/navigators-flagship-mantle?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_shoulder_mail_kultirasquest_b_01.jpg'),
-- Mail - Chest
('Mail', 'Chest', 'Longstrider''s Vest', 'Wrath of the Lich King', 'Crit', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=129890/longstriders-vest?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_chest_mail_11.jpg'),
('Mail', 'Chest', 'Ghostworld Chestguard', 'Cataclysm', 'Crit', 'Mastery', 25, NULL,
 'https://www.wowhead.com/item=133527/ghostworld-chestguard?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_chest_mail_raidshaman_k_01.jpg'),
('Mail', 'Chest', 'Leyguard Cuirass', 'Legion', 'Haste', 'Crit', 25, NULL,
 'https://www.wowhead.com/item=187585/leyguard-cuirass?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_chest_mail_legionendgame_c_01.jpg'),
('Mail', 'Chest', 'Elysian Pathfinder''s Mail', 'Shadowlands', 'Haste', 'Mastery', 25, NULL,
 'https://www.wowhead.com/item=256353/elysian-pathfinders-mail?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_chest_mail_oribosdungeon_c_01.jpg'),
-- Mail - Wrist
('Mail', 'Wrist', 'Slimescale Bracers', 'Classic', 'Haste', 'Crit', 25, NULL,
 'https://www.wowhead.com/item=225183/slimescale-bracers?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_jewelry_ring_03.jpg'),
('Mail', 'Wrist', 'Dragonbelly Bracers', 'Cataclysm', 'Crit', 'Mastery', 25, NULL,
 'https://www.wowhead.com/item=133534/dragonbelly-bracers?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_bracer_mail_raidhunter_k_01.jpg'),
('Mail', 'Wrist', 'Stormsong Mariner''s Cuff', 'Battle for Azeroth', 'Crit', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=243558/stormsong-mariners-cuff?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_bracer_mail_kultirasdungeon_c_01.jpg'),
-- Mail - Hands
('Mail', 'Hands', 'Logsplitters', 'Wrath of the Lich King', 'Haste', 'Crit', 25, NULL,
 'https://www.wowhead.com/item=129877/logsplitters?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_gauntlets_84.jpg'),
('Mail', 'Hands', 'Ravenmane''s Gloves', 'Mists of Pandaria', 'Haste', 'Mastery', 25, NULL,
 'https://www.wowhead.com/item=144046/ravenmanes-gloves?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_glove_mail_reputation_c_01.jpg'),
('Mail', 'Hands', 'Serpentine Gloves', 'Warlords of Draenor', 'Haste', 'Mastery', 25, NULL,
 'https://www.wowhead.com/item=127311/serpentine-gloves?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_glove_mail_draenorhonors2_c_01.jpg'),
-- Mail - Waist
('Mail', 'Waist', 'Aftershock Waistguard', 'Burning Crusade', 'Haste', NULL, 25, NULL,
 'https://www.wowhead.com/item=129853/aftershock-waistguard?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_belt_13.jpg'),
('Mail', 'Waist', 'Cord of Dragon Sinew', 'Cataclysm', 'Mastery', 'Crit', 25, NULL,
 'https://www.wowhead.com/item=133530/cord-of-dragon-sinew?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_belt_mail_raidhunter_k_01.jpg'),
('Mail', 'Waist', 'Ironstudded Scale Girdle', 'Warlords of Draenor', 'Haste', 'Crit', 25, NULL,
 'https://www.wowhead.com/item=119372/ironstudded-scale-girdle?bonus=4811:12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_belt_mail_draenordungeon_c_01.jpg'),
-- Mail - Legs
('Mail', 'Legs', 'Rushing Storm Kilt', 'Burning Crusade', 'Haste', 'Crit', 25, NULL,
 'https://www.wowhead.com/item=129840/rushing-storm-kilt?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_pants_mail_15.jpg'),
('Mail', 'Legs', 'Locust Swarm Legguards', 'Mists of Pandaria', 'Mastery', 'Crit', 25, NULL,
 'https://www.wowhead.com/item=144058/locust-swarm-legguards?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_pant_mail_reputation_c_01.jpg'),
('Mail', 'Legs', 'Rattlekilt', 'Warlords of Draenor', 'Crit', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=119370/rattlekilt?bonus=4811:12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_robe_mail_pvpshaman_o_01.jpg'),
('Mail', 'Legs', 'Leyguard Greaves', 'Legion', 'Crit', 'Mastery', 25, NULL,
 'https://www.wowhead.com/item=187586/leyguard-greaves?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_pants_mail_legionendgame_c_01.jpg'),
-- Mail - Feet
('Mail', 'Feet', 'Caverndeep Trudgers', 'Classic', 'Mastery', 'Vers', 25, NULL,
 'https://www.wowhead.com/item=224859/caverndeep-trudgers?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_boots_01.jpg'),
('Mail', 'Feet', 'Pack-Ice Striders', 'Wrath of the Lich King', 'Crit', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=129870/pack-ice-striders?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_boots_chain_03.jpg'),
('Mail', 'Feet', 'Sandals of the Elder Sage', 'Mists of Pandaria', 'Crit', 'Mastery', 25, NULL,
 'https://www.wowhead.com/item=144049/sandals-of-the-elder-sage?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_boot_mail_reputation_c_01.jpg'),

-- Leather - Head
('Leather', 'Head', 'Adventurer''s Pith Helmet', 'Classic', 'Crit', 'Mastery', 25, NULL,
 'https://www.wowhead.com/item=224853/adventurers-pith-helmet?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_helmet_15.jpg'),
('Leather', 'Head', 'Mask of the Deceiver', 'Burning Crusade', 'Crit', NULL, 25, NULL,
 'https://www.wowhead.com/item=129836/mask-of-the-deceiver?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_helmet_73.jpg'),
('Leather', 'Head', 'Frogskin Diving Cap', 'Warlords of Draenor', 'Haste', 'Vers', 25,
 'Equip: Increases Swim Speed by 15%', 'https://www.wowhead.com/item=109057/frogskin-diving-cap?bonus=4811:12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_helm_leather_draenorquest90_b_01.jpg'),
('Leather', 'Head', 'Mask of Harmonized Spirit', 'Shadowlands', 'Mastery', 'Crit', 25, NULL,
 'https://www.wowhead.com/item=256360/mask-of-harmonized-spirit?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_helm_leather_oribosdungeon_c_01.jpg'),
-- Leather - Shoulders
('Leather', 'Shoulders', 'Whitepetal Shouldergarb', 'Mists of Pandaria', 'Crit', 'Mastery', 35, NULL,
 'https://www.wowhead.com/item=144061/whitepetal-shouldergarb?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_shoulder_leather_reputation_c_01.jpg'),
('Leather', 'Shoulders', 'Thorignir Spaulders', 'Legion', 'Haste', 'Mastery', 35, NULL,
 'https://www.wowhead.com/item=187584/thorignir-spaulders?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_shoulder_leather_legiondungeon_c_01.jpg'),
('Leather', 'Shoulders', 'Mirestained Scout''s Mantle', 'Battle for Azeroth', 'Crit', 'Haste', 35, NULL,
 'https://www.wowhead.com/item=243562/mirestained-scouts-mantle?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_shoulder_leather_zandalarquest_b_01.jpg'),
-- Leather - Chest
('Leather', 'Chest', 'Shadow Seeker''s Tunic', 'Wrath of the Lich King', 'Crit', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=129891/shadow-seekers-tunic?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_chest_leather_22.jpg'),
('Leather', 'Chest', 'Decaying Herbalist''s Robes', 'Cataclysm', 'Mastery', 'Crit', 25, NULL,
 'https://www.wowhead.com/item=133528/decaying-herbalists-robes?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_chest_leather_raiddruid_k_01.jpg'),
('Leather', 'Chest', 'Thorignir Heartguard', 'Legion', 'Vers', 'Crit', 25, NULL,
 'https://www.wowhead.com/item=187582/thorignir-heartguard?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_chest_leather_legiondungeon_c_01.jpg'),
('Leather', 'Chest', 'Mantle of Harmonized Spirit', 'Shadowlands', 'Crit', 'Vers', 25, NULL,
 'https://www.wowhead.com/item=256352/mantle-of-harmonized-spirit?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_chest_leather_oribosdungeon_c_01.jpg'),
-- Leather - Wrist
('Leather', 'Wrist', 'Unearthed Bands', 'Classic', 'Vers', 'Mastery', 25, NULL,
 'https://www.wowhead.com/item=225181/unearthed-bands?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_bracer_06.jpg'),
('Leather', 'Wrist', 'Bracers of Manifold Pockets', 'Cataclysm', 'Mastery', 'Crit', 25, NULL,
 'https://www.wowhead.com/item=133535/bracers-of-manifold-pockets?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_bracer_leather_raidrogue_k_01.jpg'),
('Leather', 'Wrist', 'Naval Officer''s Armband', 'Battle for Azeroth', 'Mastery', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=243560/naval-officers-armband?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_bracer_leather_kultirasdungeon_c_01.jpg'),
-- Leather - Hands
('Leather', 'Hands', 'Cat Burglar''s Grips', 'Wrath of the Lich King', 'Crit', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=129881/cat-burglars-grips?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_gauntlets_79.jpg'),
('Leather', 'Hands', 'Fingers of the Loneliest Monk', 'Mists of Pandaria', 'Crit', 'Mastery', 25, NULL,
 'https://www.wowhead.com/item=144045/fingers-of-the-loneliest-monk?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_glove_leather_reputation_c_01.jpg'),
('Leather', 'Hands', 'Cave Keeper Wraps', 'Warlords of Draenor', 'Haste', 'Mastery', 25, NULL,
 'https://www.wowhead.com/item=127304/cave-keeper-wraps?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_glove_leather_draenorquest90_b_01.jpg'),
-- Leather - Waist
('Leather', 'Waist', 'Belt of the Silent Path', 'Burning Crusade', 'Crit', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=129852/belt-of-the-silent-path?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_belt_03.jpg'),
('Leather', 'Waist', 'Belt of Hidden Keys', 'Cataclysm', 'Mastery', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=133529/belt-of-hidden-keys?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_belt_leather_raidrogue_k_01.jpg'),
('Leather', 'Waist', 'Whitesea''s Waistwrap', 'Warlords of Draenor', 'Haste', 'Crit', 25, NULL,
 'https://www.wowhead.com/item=116834/whiteseas-waistwrap?bonus=4811:12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_leather_draenorquest95_b_01belt.jpg'),
-- Leather - Legs
('Leather', 'Legs', 'Trousers of the Scryers'' Retainer', 'Burning Crusade', 'Haste', 'Crit', 25, NULL,
 'https://www.wowhead.com/item=129841/trousers-of-the-scryers-retainer?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_pants_leather_03.jpg'),
('Leather', 'Legs', 'Dreadsworn Slayer Legs', 'Mists of Pandaria', 'Crit', 'Mastery', 25, NULL,
 'https://www.wowhead.com/item=144057/dreadsworn-slayer-legs?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_pant_leather_reputation_c_01.jpg'),
('Leather', 'Legs', 'Dragonrider''s Tinkered Leggings', 'Warlords of Draenor', 'Crit', 'Mastery', 25, NULL,
 'https://www.wowhead.com/item=113557/dragonriders-tinkered-leggings?bonus=4811:12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_pant_leather_draenorquest90_b_01.jpg'),
('Leather', 'Legs', 'Thorignir Breeches', 'Legion', 'Crit', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=187583/thorignir-breeches?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_pant_leather_legiondungeon_c_01.jpg'),
-- Leather - Feet
('Leather', 'Feet', 'Feet of the Lynx', 'Classic', 'Haste', 'Vers', 25, NULL,
 'https://www.wowhead.com/item=224857/feet-of-the-lynx?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_boots_wolf.jpg'),
('Leather', 'Feet', 'Boots of Captain Ellis', 'Wrath of the Lich King', 'Haste', 'Crit', 25, NULL,
 'https://www.wowhead.com/item=129871/boots-of-captain-ellis?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_boots_08.jpg'),
('Leather', 'Feet', 'Tukka-Tuk''s Hairy Boots', 'Mists of Pandaria', 'Crit', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=144050/tukka-tuks-hairy-boots?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_boot_leather_reputation_c_01.jpg'),

-- Cloth - Head
('Cloth', 'Head', 'Holy Shroud', 'Classic', 'Vers', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=224854/holy-shroud?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_helmet_16.jpg'),
('Cloth', 'Head', 'Cowl of Naaru Blessings', 'Burning Crusade', 'Vers', 'Crit', 25, NULL,
 'https://www.wowhead.com/item=129837/cowl-of-naaru-blessings?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_helmet_30.jpg'),
('Cloth', 'Head', 'Zorkra''s Hood', 'Warlords of Draenor', 'Vers', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=116110/zorkras-hood?bonus=4811:12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_helm_cloth_draenorquest90_b_01.jpg'),
('Cloth', 'Head', 'Cowl of the Forsworn Seer', 'Shadowlands', 'Vers', 'Crit', 25, NULL,
 'https://www.wowhead.com/item=256359/cowl-of-the-forsworn-seer?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_helm_cloth_oribosdungeon_c_01.jpg'),
-- Cloth - Shoulders
('Cloth', 'Shoulders', 'Mantle of the Golden Sun', 'Mists of Pandaria', 'Haste', 'Crit', 35, NULL,
 'https://www.wowhead.com/item=144060/mantle-of-the-golden-sun?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_shoulder_cloth_reputation_c_01.jpg'),
('Cloth', 'Shoulders', 'Nar''thalas Scrollmantle', 'Legion', 'Haste', 'Mastery', 35, NULL,
 'https://www.wowhead.com/item=187581/narthalas-scrollmantle?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_shoulder_cloth_legiondungeon_c_01.jpg'),
('Cloth', 'Shoulders', 'Tal''aman Ambassador''s Amice', 'Battle for Azeroth', 'Crit', 'Vers', 35, NULL,
 'https://www.wowhead.com/item=243563/talaman-ambassadors-amice?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_shoulder_cloth_zandalarquest_b_01.jpg'),
-- Cloth - Chest
('Cloth', 'Chest', 'Meteor Chaser''s Raiment', 'Wrath of the Lich King', 'Haste', 'Crit', 25, NULL,
 'https://www.wowhead.com/item=129892/meteor-chasers-raiment?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_chest_cloth_78.jpg'),
('Cloth', 'Chest', 'Lightwarper Vestments', 'Cataclysm', 'Mastery', 'Crit', 25, NULL,
 'https://www.wowhead.com/item=133526/lightwarper-vestments?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_chest_robe_raidpriest_k_01.jpg'),
('Cloth', 'Chest', 'Nar''thalas Ceremonial Tunic', 'Legion', 'Crit', 'Mastery', 25, NULL,
 'https://www.wowhead.com/item=187579/narthalas-ceremonial-tunic?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_chest_cloth_legiondungeon_c_01.jpg'),
('Cloth', 'Chest', 'Robe of the Forsworn Seer', 'Shadowlands', 'Haste', 'Mastery', 25, NULL,
 'https://www.wowhead.com/item=256351/robe-of-the-forsworn-seer?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_robe_cloth_oribosdungeon_c_01.jpg'),
-- Cloth - Wrist
('Cloth', 'Wrist', 'Aristocratic Cuffs', 'Classic', 'Haste', 'Mastery', 25, NULL,
 'https://www.wowhead.com/item=225182/aristocratic-cuffs?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_bracer_05.jpg'),
('Cloth', 'Wrist', 'Bracers of the Black Dream', 'Cataclysm', 'Crit', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=133536/bracers-of-the-black-dream?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_bracer_robe_raidpriest_k_01.jpg'),
('Cloth', 'Wrist', 'Ancient Nazmani Bracelet', 'Battle for Azeroth', 'Mastery', 'Vers', 25, NULL,
 'https://www.wowhead.com/item=243561/ancient-nazmani-bracelet?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_bracer_cloth_zandalardungeon_c_01.jpg'),
-- Cloth - Hands
('Cloth', 'Hands', 'Gloves of False Gestures', 'Wrath of the Lich King', 'Crit', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=129879/gloves-of-false-gestures?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_gauntlets_90.jpg'),
('Cloth', 'Hands', 'Gloves of Red Feathers', 'Mists of Pandaria', 'Mastery', 'Crit', 25, NULL,
 'https://www.wowhead.com/item=144044/gloves-of-red-feathers?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_gauntlets_cloth_reputation_c_01.jpg'),
('Cloth', 'Hands', 'Twisted Taboo Handwraps', 'Warlords of Draenor', 'Crit', 'Mastery', 25, NULL,
 'https://www.wowhead.com/item=127296/twisted-taboo-handwraps?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_cloth_draenordungeon_c_01glove.jpg'),
-- Cloth - Waist
('Cloth', 'Waist', 'Voodoo-Woven Belt', 'Burning Crusade', 'Crit', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=129855/voodoo-woven-belt?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_belt_03.jpg'),
('Cloth', 'Waist', 'Vestal''s Irrepressible Girdle', 'Cataclysm', 'Mastery', 'Crit', 25, NULL,
 'https://www.wowhead.com/item=133532/vestals-irrepressible-girdle?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_belt_robe_raidpriest_k_01.jpg'),
('Cloth', 'Waist', 'Fine Void-Chain Cinch', 'Warlords of Draenor', 'Mastery', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=109074/fine-void-chain-cinch?bonus=4811:12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_belt_cloth_draenorquest90_b_01.jpg'),
-- Cloth - Legs
('Cloth', 'Legs', 'Corrupted Soulcloth Pantaloons', 'Burning Crusade', 'Crit', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=129843/corrupted-soulcloth-pantaloons?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_pants_cloth_15.jpg'),
('Cloth', 'Legs', 'Leggings of the Poisoned Soul', 'Mists of Pandaria', 'Crit', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=144056/leggings-of-the-poisoned-soul?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_pants_cloth_reputation_c_01.jpg'),
('Cloth', 'Legs', 'Positive Pantaloons', 'Warlords of Draenor', 'Mastery', 'Crit', 25,
 'Equip: Gives you the "Positive" buff', 'https://www.wowhead.com/item=116765/positive-pantaloons?bonus=4811:12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_cloth_draenorquest95_b_01pant.jpg'),
('Cloth', 'Legs', 'Nar''thalas Ceremonial Legwraps', 'Legion', 'Vers', 'Mastery', 25, NULL,
 'https://www.wowhead.com/item=187580/narthalas-ceremonial-legwraps?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_pant_cloth_legiondungeon_c_01.jpg'),
-- Cloth - Feet
('Cloth', 'Feet', 'Coldstone Slippers', 'Classic', 'Crit', 'Mastery', 25, NULL,
 'https://www.wowhead.com/item=224858/coldstone-slippers?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_boots_fabric_01.jpg'),
('Cloth', 'Feet', 'Coldstep Sandals', 'Burning Crusade', 'Haste', 'Vers', 25, 'Alliance Only',
 'https://www.wowhead.com/item=171999/coldstep-sandals', 'https://wow.zamimg.com/images/wow/icons/large/inv_boots_cloth_17.jpg'),
('Cloth', 'Feet', 'Coldstep Slippers', 'Burning Crusade', 'Haste', 'Vers', 25, 'Horde Only',
 'https://www.wowhead.com/item=171995/coldstep-slippers', 'https://wow.zamimg.com/images/wow/icons/large/inv_boots_cloth_17.jpg'),
('Cloth', 'Feet', 'Coldstep Sandals', 'Wrath of the Lich King', 'Haste', 'Vers', 25, 'Alliance Only',
 'https://www.wowhead.com/item=171999/coldstep-sandals', 'https://wow.zamimg.com/images/wow/icons/large/inv_boots_cloth_17.jpg'),
('Cloth', 'Feet', 'Coldstep Slippers', 'Wrath of the Lich King', 'Haste', 'Vers', 25, 'Horde Only',
 'https://www.wowhead.com/item=171995/coldstep-slippers', 'https://wow.zamimg.com/images/wow/icons/large/inv_boots_cloth_17.jpg'),
('Cloth', 'Feet', 'Xintor''s Expeditionary Boots', 'Wrath of the Lich King', 'Crit', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=129869/xintors-expeditionary-boots?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_boots_cloth_03.jpg'),
('Cloth', 'Feet', 'Storm-Sing Sandals', 'Mists of Pandaria', 'Crit', 'Mastery', 25, NULL,
 'https://www.wowhead.com/item=144051/storm-sing-sandals?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_boots_cloth_reputation_c_01.jpg'),

-- Agnostic - Neck
('Agnostic', 'Neck', 'Evoker''s Charm', 'Wrath of the Lich King', 'Crit', 'Haste', 25, 'Has Intellect',
 'https://www.wowhead.com/item=129882/evokers-charm?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_jewelry_necklace_41.jpg'),
('Agnostic', 'Neck', 'Spiked Battleguard Choker', 'Wrath of the Lich King', 'Haste', 'Crit', 25, 'Has Strength',
 'https://www.wowhead.com/item=129883/spiked-battleguard-choker?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_jewelry_necklace_42.jpg'),
('Agnostic', 'Neck', 'Brooch of the Wailing Night', 'Wrath of the Lich King', 'Haste', 'Crit', 25, 'Has Agility',
 'https://www.wowhead.com/item=129884/brooch-of-the-wailing-night?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_jewelry_necklace_40.jpg'),
('Agnostic', 'Neck', 'Frozen Tear of Elune', 'Wrath of the Lich King', 'Crit', 'Vers', 25, 'Has Intellect',
 'https://www.wowhead.com/item=129885/frozen-tear-of-elune?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_jewelry_amulet_04.jpg'),
('Agnostic', 'Neck', 'Shard of the Crystal Forest', 'Wrath of the Lich King', 'Vers', 'Crit', 25,
 'Has Strength or Agility', 'https://www.wowhead.com/item=129886/shard-of-the-crystal-forest?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_jewelry_necklace_47.jpg'),
('Agnostic', 'Neck', 'Bloodseeker''s Solitaire', 'Mists of Pandaria', 'Haste', 'Mastery', 25, 'No Primary Stat',
 'https://www.wowhead.com/item=144052/bloodseekers-solitaire?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_jewelry_necklace_107.jpg'),
('Agnostic', 'Neck', 'Choker of the Klaxxi''va', 'Mists of Pandaria', 'Crit', 'Haste', 25, 'No Primary Stat',
 'https://www.wowhead.com/item=144053/choker-of-the-klaxxiva?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_jewelry_necklace_98.jpg'),

-- Agnostic - Back
('Agnostic', 'Back', 'Blackmetal Cape', 'Classic', 'Crit', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=225187/blackmetal-cape?bonus=11072', 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_cape_05.jpg'),
('Agnostic', 'Back', 'Farstrider Defender''s Cloak', 'Burning Crusade', 'Vers', 'Crit', 25, NULL,
 'https://www.wowhead.com/item=129830/farstrider-defenders-cloak?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_cape_naxxramas_02.jpg'),
('Agnostic', 'Back', 'Dory''s Embrace', 'Burning Crusade', 'Crit', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=129831/dorys-embrace?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_cape_20.jpg'),
('Agnostic', 'Back', 'Blood Knight War Cloak', 'Burning Crusade', 'Crit', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=129832/blood-knight-war-cloak?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_cape_18.jpg'),
('Agnostic', 'Back', 'Shawl of Shifting Probabilities', 'Burning Crusade', 'Crit', NULL, 25, NULL,
 'https://www.wowhead.com/item=129833/shawl-of-shifting-probabilities?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_cape_16.jpg'),
('Agnostic', 'Back', 'Bishop''s Cloak', 'Burning Crusade', 'Vers', NULL, 25, NULL,
 'https://www.wowhead.com/item=129834/bishops-cloak?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_cape_02.jpg'),
('Agnostic', 'Back', 'Blackguard Cape', 'Mists of Pandaria', 'Crit', 'Mastery', 25, NULL,
 'https://www.wowhead.com/item=144054/blackguard-cape?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_cape_pandaria_c_01.jpg'),
('Agnostic', 'Back', 'Sagewhisper''s Wrap', 'Mists of Pandaria', 'Vers', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=144055/sagewhispers-wrap?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_cape_pandaria_c_03.jpg'),
('Agnostic', 'Back', 'Waycrest Sentry Cloak', 'Battle for Azeroth', 'Haste', 'Vers', 25, NULL,
 'https://www.wowhead.com/item=243566/waycrest-sentry-cloak?bonus=12264', 'https://wow.zamimg.com/images/wow/icons/large/inv_cape_leather_kultirasquest_b_01.jpg'),
('Agnostic', 'Back', 'Cloak of the Tideguard', 'Battle for Azeroth', 'Mastery', 'Vers', 25, NULL,
 'https://www.wowhead.com/item=243567/cloak-of-the-tideguard?bonus=12264', 'https://wow.zamimg.com/images/wow/icons/large/inv_cape_plate_kultirasdungeon_c_01.jpg'),
('Agnostic', 'Back', 'Tidecaller''s Ritual Cape', 'Battle for Azeroth', 'Vers', 'Crit', 25, NULL,
 'https://www.wowhead.com/item=243568/tidecallers-ritual-cape?bonus=12264', 'https://wow.zamimg.com/images/wow/icons/large/inv_cape_cloth_kultirasquest_b_01.jpg'),
('Agnostic', 'Back', 'Bloodstained Shawl of Tal''Gurub', 'Battle for Azeroth', 'Mastery', 'Haste', 25, NULL,
 'https://www.wowhead.com/item=243569/bloodstained-shawl-of-talgurub?bonus=12264', 'https://wow.zamimg.com/images/wow/icons/large/inv_cape_mail_zandalarquest_b_01.jpg'),

-- Agnostic - Finger
('Agnostic', 'Finger', 'Freezing Band', 'Classic', 'Vers', 'Mastery', 25, 'Has a small amount of Frost Resistance',
 'https://www.wowhead.com/item=225186/freezing-band?bonus=11072', 'https://wow.zamimg.com/images/wow/icons/large/inv_jewelry_ring_07.jpg'),
('Agnostic', 'Finger', 'Band of Channeled Magic', 'Wrath of the Lich King', 'Haste', 'Crit', 25, 'Has Intellect',
 'https://www.wowhead.com/item=129872/band-of-channeled-magic?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_jewelry_ring_68.jpg'),
('Agnostic', 'Finger', 'Renewal of Life', 'Wrath of the Lich King', 'Vers', 'Crit', 25, 'Has Intellect',
 'https://www.wowhead.com/item=129873/renewal-of-life?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_jewelry_ring_69.jpg'),
('Agnostic', 'Finger', 'Ring of Invincibility', 'Wrath of the Lich King', 'Crit', 'Haste', 25, 'Has Agility',
 'https://www.wowhead.com/item=129874/ring-of-invincibility?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_jewelry_ring_47.jpg'),
('Agnostic', 'Finger', 'Signet of the Impregnable Fortress', 'Wrath of the Lich King', 'Vers', 'Crit', 25,
 'Has Strength or Agility', 'https://www.wowhead.com/item=129875/signet-of-the-impregnable-fortress?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_jewelry_ring_46.jpg'),
('Agnostic', 'Finger', 'Bloodshed Band', 'Wrath of the Lich King', 'Crit', 'Haste', 25, 'Has Strength',
 'https://www.wowhead.com/item=129876/bloodshed-band?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_jewelry_ring_71.jpg'),
('Agnostic', 'Finger', 'Seal of the Grand Architect', 'Cataclysm', 'Haste', 'Crit', 25, 'Has Intellect',
 'https://www.wowhead.com/item=133520/seal-of-the-grand-architect?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_jewelry_ring_90.jpg'),
('Agnostic', 'Finger', 'Band of Reconstruction', 'Cataclysm', 'Mastery', 'Vers', 25, 'Has Intellect',
 'https://www.wowhead.com/item=133521/band-of-reconstruction?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_ring_generic_1.jpg'),
('Agnostic', 'Finger', 'Ring of Torn Flesh', 'Cataclysm', 'Mastery', 'Crit', 25, 'Has Strength',
 'https://www.wowhead.com/item=133522/ring-of-torn-flesh?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_jewelry_ring_ahnqiraj_06.jpg'),
('Agnostic', 'Finger', 'Emergency Descent Loop', 'Cataclysm', 'Haste', 'Mastery', 25, 'Has Agility',
 'https://www.wowhead.com/item=133523/emergency-descent-loop?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_jewelry_ring_89.jpg'),
('Agnostic', 'Finger', 'Signet of the Resolute', 'Cataclysm', 'Vers', 'Mastery', 25, 'Has Strength',
 'https://www.wowhead.com/item=133524/signet-of-the-resolute?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_jewelry_ring_92.jpg'),

-- Agnostic - Trinket
('Agnostic', 'Trinket', 'Bloodlust Brooch', 'Burning Crusade', 'Crit', NULL, 50, 'On Use: Increase Agility',
 'https://www.wowhead.com/item=129848/bloodlust-brooch?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_monsterscales_15.jpg'),
('Agnostic', 'Trinket', 'Gnomeregan Auto-Blocker 601', 'Burning Crusade', 'Agility or Strength', NULL, 50,
 'On Use: Increase Block', 'https://www.wowhead.com/item=129849/gnomeregan-auto-blocker-601?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_battery_02.jpg'),
('Agnostic', 'Trinket', 'Icon of the Silver Crescent', 'Burning Crusade', 'Crit', NULL, 50,
 'On Use: Increase Intellect', 'https://www.wowhead.com/item=129850/icon-of-the-silver-crescent?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_weapon_shortblade_23.jpg'),
('Agnostic', 'Trinket', 'Essence of the Martyr', 'Burning Crusade', 'Intellect', NULL, 50, 'On Use: Increase Vers',
 'https://www.wowhead.com/item=129851/essence-of-the-martyr?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_valentineperfumebottle.jpg'),
('Agnostic', 'Trinket', 'Emblem of Fury', 'Burning Crusade', 'Crit', NULL, 50, 'On Use: Increase Strength',
 'https://www.wowhead.com/item=129937/emblem-of-fury?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_jewelry_talisman_09.jpg'),
('Agnostic', 'Trinket', 'Sundial of the Exalted', 'Wrath of the Lich King', 'Crit', NULL, 50, 'Equip: Intellect Proc',
 'https://www.wowhead.com/item=129893/sundial-of-the-exiled?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/ability_hunter_readiness.jpg'),
('Agnostic', 'Trinket', 'Valor Medal of the First War', 'Wrath of the Lich King', 'Agility or Strength', NULL, 50,
 'On Use: Increase Armor', 'https://www.wowhead.com/item=129895/valor-medal-of-the-first-war?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_qirajidol_sun.jpg'),
('Agnostic', 'Trinket', 'Mirror of Truth', 'Wrath of the Lich King', 'Crit', NULL, 50, 'Equip: Agility Proc',
 'https://www.wowhead.com/item=129896/mirror-of-truth?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_jewelry_talisman_08.jpg'),
('Agnostic', 'Trinket', 'The Egg of Mortal Essence', 'Wrath of the Lich King', 'Intellect', NULL, 50,
 'Equip: Haste Proc (on Heal spells)', 'https://www.wowhead.com/item=129897/the-egg-of-mortal-essence?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_egg_05.jpg'),
('Agnostic', 'Trinket', 'Mark of Supremacy', 'Wrath of the Lich King', 'Haste', NULL, 50, 'On Use: Increase Strength',
 'https://www.wowhead.com/item=129898/mark-of-supremacy?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_gem_bloodstone_03.jpg'),
('Agnostic', 'Trinket', 'Kiroptyric Sigil', 'Cataclysm', 'Haste', NULL, 50, 'On Use: Increase Agility',
 'https://www.wowhead.com/item=133537/kiroptyric-sigil?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_qiraj_jewelengraved.jpg'),
('Agnostic', 'Trinket', 'Bottled Wishes', 'Cataclysm', 'Haste', NULL, 50, 'On Use: Increase Intellect',
 'https://www.wowhead.com/item=133538/bottled-wishes?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_potion_109.jpg'),
('Agnostic', 'Trinket', 'Reflection of the Light', 'Cataclysm', 'Vers', NULL, 50, 'On Use: Increase Intellect',
 'https://www.wowhead.com/item=133539/reflection-of-the-light?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/item_uncutmetagemb.jpg'),
('Agnostic', 'Trinket', 'Rotting Skull', 'Cataclysm', 'Crit', NULL, 50, 'On Use: Increase Strength',
 'https://www.wowhead.com/item=133540/rotting-skull?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_bone_orcskull_01.jpg'),
('Agnostic', 'Trinket', 'Fire of the Deep', 'Cataclysm', 'Mastery', NULL, 50, 'On Use: Increase Dodge',
 'https://www.wowhead.com/item=133541/fire-of-the-deep?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/spell_fire_burnout.jpg'),
('Agnostic', 'Trinket', 'Shado-Pan Dragon Gun', 'Mists of Pandaria', NULL, NULL, 50, 'On Use: AoE Fire Damage',
 'https://www.wowhead.com/item=144070/shado-pan-dragon-gun?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_dragonkite_01.jpg');


-- =============================================================
-- WEAPONS
-- Columns: weapon_slot, weapon_stat, weapon_type, name,
--          expansion, primary_stat, secondary_stat, cost,
--          notes, wowhead_url
-- =============================================================

INSERT INTO weapons (weapon_slot, weapon_stat, weapon_type, name, expansion, primary_stat, secondary_stat, cost, notes,
                     wowhead_url, icon_url)
VALUES

-- Strength
('2H', 'Strength', 'Sword', 'Lightforged Blade', 'Classic', 'Crit', 'Haste', 100, NULL,
 'https://www.wowhead.com/item=225189/lightforged-blade?bonus=11072', 'https://wow.zamimg.com/images/wow/icons/large/inv_sword_39.jpg'),
('2H', 'Strength', 'Axe', 'Pendulum of Doom', 'Classic', 'Crit', NULL, 100, 'Equip: Damage Proc',
 'https://www.wowhead.com/item=225190/pendulum-of-doom?bonus=11072', 'https://wow.zamimg.com/images/wow/icons/large/inv_weapon_halberd_08.jpg'),
('1H', 'Strength', 'Axe', 'Flurry Axe', 'Classic', NULL, NULL, 50, 'Equip: Haste Proc',
 'https://www.wowhead.com/item=225199/flurry-axe?bonus=11072', 'https://wow.zamimg.com/images/wow/icons/large/inv_axe_17.jpg'),
('2H', 'Strength', 'Axe', 'The Blade of the Harbingers', 'Burning Crusade', 'Crit', 'Haste', 100, '1c Transmog Cost',
 'https://www.wowhead.com/item=129827/the-blade-of-harbingers?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_axe_04.jpg'),
('1H', 'Strength', 'Sword', 'Sword of Unyielding Force', 'Burning Crusade', 'Crit', 'Haste', 50, NULL,
 'https://www.wowhead.com/item=129861/sword-of-unyielding-force?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_jewelry_talisman_15.jpg'),
('Off-Hand', 'Strength or Intellect', 'Shield', 'Mazthoril Honor Shield', 'Burning Crusade', 'Crit', NULL, 35, NULL,
 'https://www.wowhead.com/item=129846/mazthoril-honor-shield?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_shield_37.jpg'),
('Off-Hand', 'Strength or Intellect', 'Shield', 'Azure-Shield of Coldarra', 'Burning Crusade', 'Crit', 'Vers', 35, NULL,
 'https://www.wowhead.com/item=129847/azure-shield-of-coldarra?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_shield_33.jpg'),
('2H', 'Strength', 'Sword', 'Forgotten Champion''s Blade', 'Warlords of Draenor', 'Haste', 'Mastery', 100, NULL,
 'https://www.wowhead.com/item=127339/forgotten-champions-blade?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_sword_2h_draenorcrafted_d_01_b.jpg'),
('1H', 'Agility or Strength', 'Sword', 'Shard of Scorn', 'Warlords of Draenor', 'Mastery', 'Crit', 50, NULL,
 'https://www.wowhead.com/item=113287/shard-of-scorn?bonus=4811:10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_sword_1h_draenorquest95_b_01.jpg'),
('Off-Hand', 'Strength or Intellect', 'Shield', 'Suramar Guard''s Shield', 'Legion', 'Mastery', 'Crit', 35, NULL,
 'https://www.wowhead.com/item=187563/suramar-guards-shield?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/inv_shield_1h_silverhand_b_01.jpg'),
('Off-Hand', 'Strength or Intellect', 'Shield', 'Nightborne Arcshield', 'Legion', 'Mastery', 'Vers', 35, NULL,
 'https://www.wowhead.com/item=187564/nightborne-arcshield?bonus=10845', 'https://wow.zamimg.com/images/wow/icons/large/ability_mage_shattershield.jpg'),
('2H', 'Strength', 'Mace', 'Ashvane Ore Crusher', 'Battle for Azeroth', 'Haste', 'Crit', 100, NULL,
 'https://www.wowhead.com/item=244151/ashvane-ore-crusher?bonus=12264', 'https://wow.zamimg.com/images/wow/icons/large/inv_mace_2h_kultirasquest_b_01.jpg'),
('2H', 'Strength', 'Sword', 'Reclaimed Ancestral Blade of the Deeps', 'Battle for Azeroth', 'Vers', 'Mastery', 100,
 NULL, 'https://www.wowhead.com/item=244153/reclaimed-ancestral-blade-of-the-deeps?bonus=12264', 'https://wow.zamimg.com/images/wow/icons/large/inv_sword_2h_deepjinyu_b_01.jpg'),
('2H', 'Strength', 'Polearm', 'Siren Slayer''s Trident', 'Battle for Azeroth', 'Vers', 'Mastery', 100, NULL,
 'https://www.wowhead.com/item=244155/siren-slayers-trident?bonus=12264', 'https://wow.zamimg.com/images/wow/icons/large/inv_staff_2h_naga_a_02.jpg'),
('Off-Hand', 'Strength or Intellect', 'Shield', 'Blessed Bulwark of Zanchul', 'Battle for Azeroth', 'Mastery', 'Vers',
 35, NULL, 'https://www.wowhead.com/item=244157/blessed-bulwark-of-zanchul?bonus=12264', 'https://wow.zamimg.com/images/wow/icons/large/inv_shield_1h_battledungeon_c_02.jpg'),
('1H', 'Strength', 'Axe', 'Mugambala Champion''s Axe', 'Battle for Azeroth', 'Crit', 'Mastery', 50, NULL,
 'https://www.wowhead.com/item=244161/mugambala-champions-axe?bonus=12264', 'https://wow.zamimg.com/images/wow/icons/large/inv_axe_1h_zandalarquest_b_02.jpg'),
('2H', 'Agility or Strength', 'Polearm', 'Kyrian Sky Splitter', 'Shadowlands', 'Haste', 'Crit', 100, NULL,
 'https://www.wowhead.com/item=256336/kyrian-sky-splitter?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_polearm_2h_oribosdungeon_c_01.jpg'),
('2H', 'Strength', 'Axe', 'The Price Adjuster', 'Shadowlands', 'Crit', 'Mastery', 100, NULL,
 'https://www.wowhead.com/item=256337/the-price-adjuster?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_axe_2h_broker_c_01.jpg'),
('1H', 'Strength', 'Sword', 'Anima Drinker''s Rapier', 'Shadowlands', 'Crit', 'Vers', 50, NULL,
 'https://www.wowhead.com/item=256339/anima-drinkers-rapier?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_sword_1h_kultirasquest_b_01.jpg'),
('Off-Hand', 'Strength or Intellect', 'Shield', 'Fallen Ascendant''s Bulwark', 'Shadowlands', 'Haste', 'Crit', 50, NULL,
 'https://www.wowhead.com/item=256348/fallen-ascendants-bulwark?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_shield_1h_bastionquest_b_01.jpg'),

-- Agility
('1H', 'Agility', 'Fist Weapon', 'Lefty''s Brass Knuckle', 'Classic', 'Haste', 'Crit', 50, NULL,
 'https://www.wowhead.com/item=225188/leftys-brass-knuckle?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_gauntlets_11.jpg'),
('1H', 'Agility', 'Dagger', 'Gut Ripper', 'Classic', NULL, NULL, 50, 'Equip: Physical Damage Proc',
 'https://www.wowhead.com/item=225191/gut-ripper?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_sword_13.jpg'),
('Ranged', 'Agility', 'Bow', 'Bow of Searing Arrows', 'Classic', NULL, NULL, 100, 'Equip: Fire Damage Proc',
 'https://www.wowhead.com/item=225192/bow-of-searing-arrows?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_weapon_bow_09.jpg'),
('1H', 'Agility', 'Axe', 'Axe of the Deep Wounds', 'Classic', NULL, NULL, 50, 'Equip: Nature Damage Proc',
 'https://www.wowhead.com/item=225195/axe-of-the-deep-woods?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_axe_07.jpg'),
('2H', 'Agility', 'Polearm', 'Grimlok''s Charge', 'Classic', 'Haste', 'Mastery', 100, NULL,
 'https://www.wowhead.com/item=225196/grimloks-charge?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_spear_08.jpg'),
('2H', 'Agility', 'Staff', 'Warden Staff', 'Classic', 'Mastery', 'Vers', 50, NULL,
 'https://www.wowhead.com/item=225198/warden-staff?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_staff_29.jpg'),
('1H', 'Agility', 'Dagger', 'Alcor''s Sunrazor', 'Classic', NULL, NULL, 50, 'On Use: Deal Fire Damage',
 'https://www.wowhead.com/item=225200/alcors-sunrazor?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_sword_34.jpg'),
('Ranged', 'Agility', 'Gun', 'Precisely Calibrated Rifle', 'Classic', 'Crit', 'Vers', 100, NULL,
 'https://www.wowhead.com/item=225201/precisely-calibrated-rifle?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_weapon_rifle_06.jpg'),
('2H', 'Agility', 'Staff', 'Staff of the Forest Lord', 'Burning Crusade', 'Crit', 'Vers', 100, '1c Transmog Cost',
 'https://www.wowhead.com/item=129829/staff-of-the-forest-lord?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_staff_12.jpg'),
('Ranged', 'Agility', 'Crossbow', 'Crossbow of Relentless Striles', 'Burning Crusade', 'Crit', 'Vers', 50,
 '1c Transmog Cost', 'https://www.wowhead.com/item=129845/crossbow-of-relentless-strikes?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_weapon_crossbow_26.jpg'),
('1H', 'Agility', 'Fist Weapon', 'Vanir''s Fist of Brutality', 'Burning Crusade', 'Haste', NULL, 50, '1c Transmog Cost',
 'https://www.wowhead.com/item=129856/vanirs-fist-of-brutality?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_weapon_hand_16.jpg'),
('1H', 'Agility', 'Dagger', 'The Mutilator', 'Burning Crusade', 'Crit', NULL, 50, '1c Transmog Cost',
 'https://www.wowhead.com/item=129931/the-mutilator?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_weapon_shortblade_78.jpg'),
('Ranged', 'Agility', 'Gun', 'Blammo''s Blammer', 'Warlords of Draenor', NULL, NULL, 100, 'Equip: Fire Damage Proc',
 'https://www.wowhead.com/item=119226/blammos-blammer?bonus=4811:12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_firearm_2h_rifle_draenorhonor_c_01.jpg'),
('Ranged', 'Agility', 'Bow', 'Argussian Reach Longbow', 'Legion', 'Crit', 'Haste', 100, NULL,
 'https://www.wowhead.com/item=187565/argussian-reach-longbow?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_bow_1h_pvpdraenors2_d_01.jpg'),
('1H', 'Agility', 'Sword', 'Nightborne Arcsaber', 'Legion', 'Mastery', 'Haste', 50, NULL,
 'https://www.wowhead.com/item=187567/nightborne-arcsaber?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/ability_paladin_swiftretribution.jpg'),
('2H', 'Agility', 'Polearm', 'Freehold Boarding Halberd', 'Battle for Azeroth', 'Vers', 'Mastery', 100, NULL,
 'https://www.wowhead.com/item=244154/freehold-boarding-halberd?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_polearm_2h_battledungeon_c_01.jpg'),
('Ranged', 'Agility', 'Bow', 'Crackling Stormbow of the Devoted', 'Battle for Azeroth', 'Mastery', 'Crit', 100, NULL,
 'https://www.wowhead.com/item=244156/crackling-stormbow-of-the-devoted?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_bow_1h_battledungeon_c_01.jpg'),
('1H', 'Agility', 'Dagger', 'Tol''Dagor Pocket Shank', 'Battle for Azeroth', 'Vers', 'Mastery', 50, NULL,
 'https://www.wowhead.com/item=244159/toldagor-pocket-shank?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_knife_1h_dagger_a_05.jpg'),
('1H', 'Agility', 'Mace', 'Bondo''s Spare Mechano-Clamps', 'Battle for Azeroth', 'Vers', 'Mastery', 50, NULL,
 'https://www.wowhead.com/item=244162/bondos-spare-mechano-clamps?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_mace_1h_enprofession_c_01.jpg'),
('1H', 'Agility', 'Dagger', 'Dagger of Forgotten Vows', 'Shadowlands', 'Mastery', 'Crit', 50, NULL,
 'https://www.wowhead.com/item=256338/dagger-of-forgotten-vows?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_knife_1h_oribosdungeon_c_01.jpg'),
('Ranged', 'Agility', 'Bow', 'Skyguard''s Longbow', 'Shadowlands', 'Mastery', 'Crit', 100, NULL,
 'https://www.wowhead.com/item=256340/skyguards-longbow?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_bow_1h_oribosdungeon_c_01.jpg'),
('1H', 'Agility', 'Warglaive', 'Warglaives of Devotion', 'Shadowlands', 'Vers', 'Mastery', 50, NULL,
 'https://www.wowhead.com/item=256349/warglaives-of-devotion?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_glaive_1h_bastionquest_b_01.jpg'),

-- Intellect
('2H', 'Intellect', 'Staff', 'Elemental Mage Staff', 'Classic', 'Crit', 'Mastery', 100, NULL,
 'https://www.wowhead.com/item=225193/elemental-mage-staff?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_staff_07.jpg'),
('1H', 'Intellect', 'Wand', 'Crimson Shocker', 'Classic', 'Crit', 'Mastery', 50, NULL,
 'https://www.wowhead.com/item=225197/crimson-shocker?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_staff_13.jpg'),
('1H', 'Intellect', 'Dagger', 'Scryer''s Blade of Focus', 'Burning Crusade', 'Crit', 'Haste', 50, '1c Transmog Cost',
 'https://www.wowhead.com/item=129857/scryers-blade-of-focus?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_weapon_shortblade_78.jpg'),
('1H', 'Intellect', 'Mace', 'Gavel of Naaru Blessings', 'Burning Crusade', 'Crit', 'Haste', 50, '1c Transmog Cost',
 'https://www.wowhead.com/item=129858/gavel-of-naaru-blessings?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_mace_82.jpg'),
('2H', 'Intellect', 'Staff', 'Staff of the Soul-Eater', 'Burning Crusade', 'Crit', 'Haste', 100, '1c Transmog Cost',
 'https://www.wowhead.com/item=129828/staff-of-the-soul-eater?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_staff_73.jpg'),
('Off-Hand', 'Intellect', 'Held In Off-hand', 'Talisman of Kalecgos', 'Burning Crusade', 'Crit', 'Haste', 35, NULL,
 'https://www.wowhead.com/item=129839/talisman-of-kalecgos?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_offhand_outlandraid_02.jpg'),
('1H', 'Intellect', 'Dagger', 'Shadowspeaker''s Shard', 'Warlords of Draenor', 'Crit', 'Vers', 50,
 'Suitable Rogue weapon if you believe hard enough',
 'https://www.wowhead.com/item=119396/shadowspeakers-shard?bonus=4811:12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_knife_1h_draenordungeon_c_02.jpg'),
('1H', 'Intellect', 'Mace', 'Arcsmasher', 'Legion', 'Crit', 'Vers', 50, NULL,
 'https://www.wowhead.com/item=187566/arcsmasher?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_mace_41.jpg'),
('2H', 'Intellect', 'Staff', 'Warpcaster''s Staff', 'Legion', 'Crit', 'Vers', 100, NULL,
 'https://www.wowhead.com/item=187578/warpcasters-staff?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_staff_2h_draenorchallenge_d_01.jpg'),
('Off-Hand', 'Intellect', 'Held In Off-hand', 'Seaglass Ritual Rod', 'Battle for Azeroth', 'Vers', 'Mastery', 35, NULL,
 'https://www.wowhead.com/item=244150/seaglass-ritual-rod?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_wand_1h_kultirasquest_b_01.jpg'),
('2H', 'Intellect', 'Staff', 'Pilfered Golden Scepter', 'Battle for Azeroth', 'Haste', 'Crit', 100, NULL,
 'https://www.wowhead.com/item=244152/pilfered-golden-scepter?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_staff_2h_zandalarquest_b_02.jpg'),
('1H', 'Intellect', 'Dagger', 'Azerite-Carved Ritual Kris', 'Battle for Azeroth', 'Vers', 'Mastery', 50, NULL,
 'https://www.wowhead.com/item=244158/azerite-carved-ritual-kris?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_knife_1h_naga_c_01.jpg'),
('1H', 'Intellect', 'Mace', 'Junkyard Clobberstick', 'Battle for Azeroth', 'Vers', 'Mastery', 50, NULL,
 'https://www.wowhead.com/item=244160/junkyard-clobberstick?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_mace_1h_troggking_c_01.jpg'),
('Off-Hand', 'Intellect', 'Held In Off-hand', 'Sacred Bell of the Ascended', 'Shadowlands', 'Mastery', 'Vers', 50, NULL,
 'https://www.wowhead.com/item=254868/sacred-bell-of-the-ascended?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_offhand_1h_bastionquest_b_01.jpg'),
('2H', 'Intellect', 'Staff', 'Faithspire Redeemer', 'Shadowlands', 'Mastery', 'Haste', 100, NULL,
 'https://www.wowhead.com/item=256341/faithspire-redeemer?bonus=12377', 'https://wow.zamimg.com/images/wow/icons/large/inv_staff_2h_oribosdungeon_c_01.jpg');